### ISSUE TITLE
Problem in getting TRC20Contract decimals

### ISSUE THREAD

**Issue by TheMajical** [tronprotocol/trident#118]
Hi, I'm trying to extract a token decimals by its ContractAddress.
here is my code based on the documents:
`var contract = client.getContract(contractAddress);
        Trc20Contract token = new Trc20Contract(contract, "410000000000000000000000000000000000000000", client);
        return token.decimals();`
       I tested it with USDT Contract with "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t" address
       and my code fails with this error:
       Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0
	at java.base/java.util.Collections$EmptyList.get(Collections.java:4588)
	at org.tron.trident.proto.Response$TransactionExtention.getConstantResult(Response.java:3716)
	
	any idea which part I'm doing wrong or any alternative way to extract decimals?

**Comment by lxcmyf** [comment]
@TheMajical 
Please refer to:https://developers.tron.network/reference/trc-20-contracts

**Comment by endiaoekoe** [comment]
> Hi, I'm trying to extract a token decimals by its ContractAddress. here is my code based on the documents: ![image](https://private-user-images.githubusercontent.com/36631455/313237107-b94a1138-4cac-4321-af7f-224475607b3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NTY4ODksIm5iZiI6MTcxMDY1NjU4OSwicGF0aCI6Ii8zNjYzMTQ1NS8zMTMyMzcxMDctYjk0YTExMzgtNGNhYy00MzIxLWFmN2YtMjI0NDc1NjA3YjNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDA2MjMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiMzM1Nzg2YzFjYmIyNGNlZTZhMjI5NWZhNzBmMWU2MGFhNjU2MGJmN2QzYjM4Njk4MzI2ZmU3ZGM4ZTNkMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DYp5e_fl9heDPE7ek4-ExOu3Uxt-FWYS-g8fYWc-lek)
> 
> `var contract = client.getContract(contractAddress); Trc20Contract token = new Trc20Contract(contract, "410000000000000000000000000000000000000000", client); return token.decimals();` I tested it with USDT Contract with "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t" address and my code fails with this error: Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0 at java.base/java.util.Collections$EmptyList.get(Collections.java:4588) at org.tron.trident.proto.Response$TransactionExtention.getConstantResult(Response.java:3716)
> 
> ```
> any idea which part I'm doing wrong or any alternative way to extract decimals?
> ```

hi, @TheMajical 
I just debugged the codes you provided above, seems work well on my machine.it returns 6 when invoking ' token.decimals()'
![image](https://github.com/tronprotocol/trident/assets/7970865/57ad25fd-d803-4fd0-a7d1-c1bc129495e8)

could you make sure you run your code in mainnet config.cz contract address ’TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t‘ may not be deployed well in Nile testnet or other testnet,but we can make sure, it deployed well in mainnet.
