### ISSUE TITLE
智能合约 Parameter 地址解码，使用 8-72 发生错误！

### ISSUE THREAD

**Issue by tianfangdao** [tronprotocol/trident#53]
jdk-17.0.2
[官方文档解码示例](https://cn.developers.tron.network/reference/encode-decode#%E5%8F%82%E6%95%B0%E8%A7%A3%E7%A0%81)

目前我使用 str.substring(32, 72) 并不会报错，不过并不清楚这样做是否会有其他的后遗症。

--- error example 1 ---
交易成功,ID：68ca010975471efc8471cc7e4bda8da649c0890fe2a680f04533badf7f96e2c5
合约类型：TriggerSmartContract
Any parameter =
a9059cbb000000000000000000000041aaf60cd880f0ce0173952a83cbf54b90804e896100000000000000000000000000000000000000000000000000000000434b2c40

--- error example 2 ---
交易成功,ID：676a77e2b090922c8764fa16613be25f8da7186ea13930285d18aa71a406e0b2
合约类型：TriggerSmartContract
Any parameter =
a9059cbb00000000000000000000004170227084cfb88fb7a68b64e51c6c6cde4be9d34b0000000000000000000000000000000000000000000000000000000002faf080

```Java

/**
 * 转账事件解析
 *
 * @param data 数据
 * @return 到账地址+金额
 */
public static TransferFuncValue transferParse(String data) throws CustomParserException {
    // 函数选择器
    String func = data.substring(0, 8);
    if (!"a9059cbb".equals(func)) {
        throw new CustomParserException("该数据非交易转账");
    }
    // 收款人地址
    String toAddress = data.substring(8, 72);
    // 发送金额
    String amount = data.substring(72, 136);
    try {

        Type addressType = TypeDecoder.instantiateType("address", toAddress);
        Type amountType = TypeDecoder.instantiateType("uint256", amount);

        return new TransferFuncValue(addressType.getValue().toString(), new BigInteger(amountType.getValue().toString()));
    } catch (Exception e) {
        throw new CustomParserException("无法解析transfer数据:" + data, e.getCause());
    }
}

```

```Java
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.tron.trident.abi.TypeDecoder.instantiateAtomicType(TypeDecoder.java:228)
	at org.tron.trident.abi.TypeDecoder.instantiateType(TypeDecoder.java:53)
	at org.tron.trident.abi.TypeDecoder.instantiateType(TypeDecoder.java:43)
	at org.tron.eazywork.util.SmartContractParser.transferParse(SmartContractParser.java:52)
	at org.tron.mix.tron.DemoTest.parse(DemoTest.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.UnsupportedOperationException: Bit size must be 8 bit aligned, and in range 0 < bitSize <= 256
	at org.tron.trident.abi.datatypes.IntType.<init>(IntType.java:26)
	at org.tron.trident.abi.datatypes.Uint.<init>(Uint.java:24)
	at org.tron.trident.abi.datatypes.Address.<init>(Address.java:50)
	... 79 more
```

**Comment by Cletitia** [comment]
我不明白你所说的后遗症具体指什么，需要描述清楚。

**Comment by tianfangdao** [comment]
> 我不明白你所说的后遗症具体指的是什么，需要清楚描述。

文档指出 DATA.substring(8,72)是收款人地址 ，而我并非按着它来编写的。
群里有高手指点换成 32-72 ，的确是可以运行，不会像之前出现错误解析的情况。
然而，这样做有什么后遗症，我肯定是不知道的，只能猜测是文档的错误或是 trident 有问题，在此求证。

**Comment by Cletitia** [comment]
每一个非dynamic参数固定占位32字节，长度不够则用零补齐。
你需要了解abi的编码规则，参考solidity任意版本的官方文档。

**Comment by tianfangdao** [comment]
> 每一个非dynamic参数固定占位32字节，长度不够则用零补齐。 你需要了解abi的编码规则，参考solidity任意版本的官方文档。

所有我自己提前处理下就行了

**Comment by daxingxinga1234** [comment]
> > 我不明白你所说的后遗症具体指的是什么，需要清楚描述。
> 
> 文档指出 DATA.substring(8,72)是收款人地址 ，而我并非按着它来编写的。 群里有高手指点换成 32-72 ，的确是可以运行，不会像之前出现错误解析的情况。 然而，这样做有什么后遗症，我肯定是不知道的，只能猜测是文档的错误或是 trident 有问题，在此求证。

换成32-72 地址会解密错误，不是真实的转账地址，切记！ 我定位了老半天才发现的
