### ISSUE TITLE
生产jar包依赖问题

### ISSUE THREAD

**Issue by bamoop** [tronprotocol/trident#64]
请问要怎么去打jar包呀，我用gradle打jar包，应用依赖的时候报错了

Exception in thread "main" java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider
	at org.tron.trident.crypto.SECP256K1.<clinit>(SECP256K1.java:69)
	at org.tron.trident.crypto.SECP256K1$KeyPair.generate(SECP256K1.java:485)
	at org.tron.trident.core.key.KeyPair.generate(KeyPair.java:30)
	at com.pony.fblock.FblockApplication.main(TestApplication.java:13)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.BouncyCastleProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 4 more

**Comment by chis66** [comment]
請問,這個問題怎麽處理好的？
