### ISSUE TITLE
use ApiWrapper to request error

### ISSUE THREAD

**Issue by SuperEdison** [tronprotocol/trident#66]
jdk17 mac m1
```conf
plugins {
    id 'com.google.protobuf' version '0.8.12'
}

description 'Trident-Java gRPC core classes'

dependencies {
    implementation 'com.google.guava:guava:29.0-jre'

    implementation project(':utils')
    implementation project(':abi')

    implementation 'io.grpc:grpc-netty-shaded:1.49.2'
    implementation 'io.grpc:grpc-netty:1.49.2'
    implementation 'io.grpc:grpc-okhttp:1.49.2'
    implementation 'io.grpc:grpc-protobuf:1.49.2'
    implementation 'io.grpc:grpc-stub:1.49.2'
    compileOnly 'org.apache.tomcat:annotations-api:6.0.53' // necessary for Java 9+
    //json parsing
    implementation 'com.google.protobuf:protobuf-java-util:3.19.4'

    implementation "org.bouncycastle:bcprov-jdk18on:$bouncycastleVersion"
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.19.4'
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.49.2'
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc { }
        }
    }
    generatedFilesBaseDir = "$projectDir/src"
}
```
i upgrade the grpc version and protobuf-java version and bcprov-jdk18on, i had build full node
```log
Exception in thread "main" io.grpc.StatusRuntimeException: INTERNAL: http2 exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
	at org.tron.trident.api.WalletSolidityGrpc$WalletSolidityBlockingStub.getNowBlock2(WalletSolidityGrpc.java:341)
	at org.tron.trident.core.ApiWrapper.getNowBlockSolidity(ApiWrapper.java:1202)
	at com.example.demo.Demo1Application.main(Demo1Application.java:15)
Caused by: io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
```

**Comment by liushuyu1** [comment]
Has the problem been solved? I have the same problem

**Comment by xq-lu** [comment]
> Has the problem been solved? I have the same problem

from the error you paste, Decoding those shows "HTTP ", which probably means you are connecting to an HTTP/1.1 server, not HTTP2. Make sure you are connecting to the right one. and check your grpc endpoint port, making sure the port is configured right.
