### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by acomet** [tronprotocol/trident#75]
Caused by: java.security.NoSuchAlgorithmException: no such algorithm: ECDSA for provider BC
        at sun.security.jca.GetInstance.getService(GetInstance.java:87)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:206)
        at java.security.KeyPairGenerator.getInstance(KeyPairGenerator.java:319)
        at org.tron.trident.crypto.SECP256K1.<clinit>(SECP256K1.java:76)
        at org.tron.trident.crypto.SECP256K1.access$300(SECP256K1.java:57) 
        at org.tron.trident.crypto.SECP256K1$KeyPair.generate(SECP256K1.java:485) 
        at org.tron.trident.core.key.KeyPair.generate(KeyPair.java:30) 
        at org.tron.trident.core.ApiWrapper.generateAddress(ApiWrapper.java:195) 
        at android.view.View.performClick(View.java:7558) 
        at android.view.View.performClickInternal(View.java:7534) 
        at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0) 
        at android.view.View$PerformClick.run(View.java:29661) 
        at android.os.Handler.handleCallback(Handler.java:942) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:240) 
        at android.os.Looper.loop(Looper.java:351) 
        at android.app.ActivityThread.main(ActivityThread.java:8364) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)

**Comment by Jake151987** [comment]
@acomet The trident SDK does not support embedding in Android for now.

**Comment by acomet** [comment]
> @acomet The trident SDK does not support embedding in Android for now.

Hi,so which SDK or library can I use in Android? THX,bro

**Comment by acomet** [comment]
@Jake151987 Hi,so which SDK or library can I use in Android? THX,bro

**Comment by Jake151987** [comment]
@acomet Our suggestion is to downgrade to bcprov-jdk15on-1.65, which may still work with Android. Or you may also have a try with jdk15to18: bcprov-jdk15to18-167.jar. 

This library could be the problem of why Android does not support it. The current version implemented in Trident-Java of the library is bcprov-jdk15on-1.68.

**Comment by Jake151987** [comment]
@acomet found something you could be interested in, this could help if you are still working on Android projects.
[PUB-Trident-SDKSupportingIssueforAndroid-190423-0658.pdf](https://github.com/tronprotocol/trident/files/11269642/PUB-Trident-SDKSupportingIssueforAndroid-190423-0658.pdf)
