### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by lvgang214** [tronprotocol/trident#93]
在使用了 new KeyPair("prikey") 后 
okhttpclient 请求 报错
java.security.KeyStoreException: problem accessing trust store
	at java.base/sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:73)
	at java.base/javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:282)
	at okhttp3.internal.platform.Platform.platformTrustManager(Platform.kt:80)
	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:237)
	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:222)
	at org.example.service.impl.TronChainServiceImpl.main(TronChainServiceImpl.java:54)
Caused by: java.io.IOException: stream does not represent a PKCS12 key store
	at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engineLoad(Unknown Source)
	at java.base/java.security.KeyStore.load(KeyStore.java:1473)
	at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.loadKeyStore(TrustStoreManager.java:390)
	at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.getTrustedCerts(TrustStoreManager.java:336)
	at java.base/sun.security.ssl.TrustStoreManager.getTrustedCerts(TrustStoreManager.java:57)
	at java.base/sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:49)
	... 5 more

**Comment by lurais** [comment]
@lvgang214 hello, Can you describe in detail what you did? Is it just using new KeyPair("prikey") but not doing anything else? Did you follow the reference documentation here： https://developers.tron.network/reference/quickstart ？

**Comment by xq-lu** [comment]
> 在使用了 new KeyPair("prikey") 后 okhttpclient 请求 报错 java.security.KeyStoreException: problem accessing trust store at java.base/sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:73) at java.base/javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:282) at okhttp3.internal.platform.Platform.platformTrustManager(Platform.kt:80) at okhttp3.OkHttpClient.(OkHttpClient.kt:237) at okhttp3.OkHttpClient.(OkHttpClient.kt:222) at org.example.service.impl.TronChainServiceImpl.main(TronChainServiceImpl.java:54) Caused by: java.io.IOException: stream does not represent a PKCS12 key store at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engineLoad(Unknown Source) at java.base/java.security.KeyStore.load(KeyStore.java:1473) at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.loadKeyStore(TrustStoreManager.java:390) at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.getTrustedCerts(TrustStoreManager.java:336) at java.base/sun.security.ssl.TrustStoreManager.getTrustedCerts(TrustStoreManager.java:57) at java.base/sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:49) ... 5 more

hi, @lvgang214 
From the error message ‘Caused by: java.io.IOException: stream does not represent a PKCS12 key store’  you describe above. In your Android application that uses a keystore to Auth SSL connection, the error happened when loading the p12 file with the private key, which throws an SSL error.
The reason is most likely you may store a different keystore by mistake. So make sure to work on the same Keystore.
